image: robertcnelson/debian-bookworm-beagle-devscripts-manifesto:latest

pages:
  tags:
    - docker-arm64
  stage: build
  script:
    - sed -i -e "s:20230616:$(LANG=C date +%Y%m%d):g" debian/changelog
    - debuild -us -uc
    - mkdir -p ./public/pool/
    - mkdir -p ./public/dists/stable/main/binary-arm64/
    - cp -v ../*.deb ./public/pool/ || true
    - cd ./public ; dpkg-scanpackages ./pool/ | gzip > ./dists/stable/main/binary-arm64/Packages.gz || true ; cd ../
    - apindex public
  artifacts:
    paths:
      - public
  only:
  - mikroe
