#!/usr/bin/python
# -*- coding: utf-8 -*-

import argparse
import json
import sys
import os
import time

pathprefix = ''

if os.path.exists('/home/debian/manifesto/'):
    pathprefix = '/home/debian/manifesto/'


def removeclick():
    parser = \
        argparse.ArgumentParser(description='CLI for removing Mikroe Clicks through Greybus'
                                )
    parser.add_argument('click', type=str, nargs=1,
                        help='Click name : rtc6 , weather, microSD, oledc, oledb '
                        )
    args = parser.parse_args()
    with open(pathprefix + 'clicks.json') as f:
        clickdatajson = json.load(f)
    clickdata = clickdatajson[args.click[0]]
    if clickdata['type'] == 'i2c':
        if clickdata['class'] == 'ordinary':
            os.system('echo ' + ' ' + clickdata['address']
                    + ' | sudo tee /sys/class/i2c-adapter/i2c-3/delete_device'
                    )        
        elif clickdata['class'] == 'platform':
            os.system('sudo rmmod -f mikrobus_i2c_device')
        if os.path.isfile('/tmp/gbsim/hotplug-module/' + args.click[0]
                    + '.mnfb'):
            os.remove('/tmp/gbsim/hotplug-module/' + args.click[0]
                        + '.mnfb')
    elif clickdata['type'] == 'spi':
        if clickdata['class'] == 'ordinary':
            if os.path.isfile('/tmp/gbsim/hotplug-module/'
                              + args.click[0] + '.mnfb'):
                os.remove('/tmp/gbsim/hotplug-module/' + args.click[0]
                          + '.mnfb')
        elif clickdata['class'] == 'display':
            os.system('sudo rmmod -f ' + clickdata['driver'])
            os.system('sudo rmmod -f fbtft_device')
            os.system('sudo rmmod -f fbtft')
            if os.path.isfile('/tmp/gbsim/hotplug-module/'
                              + args.click[0] + '.mnfb'):
                os.remove('/tmp/gbsim/hotplug-module/' + args.click[0]
                          + '.mnfb')
        elif clickdata['class'] == 'platform':
            os.system('sudo rmmod -f mikrobus_spi_device')
            if os.path.isfile('/tmp/gbsim/hotplug-module/'
                              + args.click[0] + '.mnfb'):
                os.remove('/tmp/gbsim/hotplug-module/' + args.click[0]
                          + '.mnfb')


if __name__ == '__main__':
    removeclick()