#!/usr/bin/python
# -*- coding: utf-8 -*-

import argparse
import json
import sys
import os
import time

pathprefix = ''

if os.path.exists('/home/debian/manifesto/'):
    pathprefix = '/home/debian/manifesto/'


def removeclick():
    parser = \
        argparse.ArgumentParser(description='CLI for removing Mikroe Clicks through Greybus'
                                )
    parser.add_argument('click', type=str, nargs=1,
                        help='Click name : rtc6 , weather, microSD, oledc, oledb '
                        )
    parser.add_argument('port', type=str, nargs=1,
                        help='Mikrobus Slot number : p1 , p2 ..')
    args = parser.parse_args()
    if args.port[0].lower() == 'p1':
        gbsim = 0
    elif args.port[0].lower() == 'p2':
        gbsim = 1
    elif args.port[0].lower() == 'p3':
        gbsim = 2
    elif args.port[0].lower() == 'p4':
        gbsim = 3
    with open(pathprefix + 'clicks.json') as f:
        clickdatajson = json.load(f)
    clickdata = clickdatajson[args.click[0]]
    if clickdata['type'] == 'i2c':
        if clickdata['class'] == 'ordinary':
            os.system('echo ' + ' ' + clickdata['address']
                    + ' | sudo tee /sys/class/i2c-adapter/i2c-3/delete_device'
                    )        
        elif clickdata['class'] == 'platform':
            os.system('sudo rmmod -f mikrobus_i2c_device')
    elif clickdata['type'] == 'spi':
        if clickdata['class'] == 'display':
            os.system('sudo rmmod -f ' + clickdata['driver'])
            os.system('sudo rmmod -f fbtft_device')
            os.system('sudo rmmod -f fbtft')
        elif clickdata['class'] == 'platform':
            os.system('sudo rmmod -f mikrobus_spi_device')
    
    if os.path.isfile('/tmp/gbsim' + str(gbsim) + '/hotplug-module/' + args.click[0]
                     + '.mnfb'):
        os.remove('/tmp/gbsim' + str(gbsim) + '/hotplug-module/' + args.click[0]
                        + '.mnfb')

if __name__ == '__main__':
    removeclick()